### PR TITLE
The service station

### PR DESCRIPTION
**Pull request by StannisMod**
Adds the service station block to automatically repair the linked rockets using nearest precision assemblers.

Also some fixes, refactorings and helper classes.

### CODE REVIEW

**Comment by dercodeKoenig** [comment]
because this is a big change, I will not read every single code change because it would take a lot of time. So I just ask this questions that may cause bugs in the code:

1: How does the system handle one of the following events during repair of a part:
- rocket launched
- rocket disassembled
- assembler destroyed
- service station destroyed

2: how does the service station scan for assemblers around it?

3: when a part is placed in the assembler, will it be removed from the storagechunk and will rocketstats get recalculated? (thrust, weight) This is important for when the rocket is disassembled during repair so it does not dulicate parts

4: what happens when the player removes the repaired part from the assembler output before the station can take it back?

5: are the bugs reported from discord fixed? 


If the system is ready and merged I will probably modify it to make little robots move the parts around into the assembler and back to the rocket

**Comment by dercodeKoenig** [comment]
this update may be great for some people who love realism but others may not like it to worry about rocket repairs. there has to be a config to disable rocket damage system.

**Comment by StannisMod** [comment]
> this update may be great for some people who love realism but others may not like it to worry about rocket repairs. there has to be a config to disable rocket damage system.

There is a config option

**Comment by StannisMod** [comment]
> because this is a big change, I will not read every single code change because it would take a lot of time. So I just ask this questions that may cause bugs in the code:
> 
> 1: How does the system handle one of the following events during repair of a part:
> 
> * rocket launched
> * rocket disassembled
> * assembler destroyed
> * service station destroyed
> 
> 2: how does the service station scan for assemblers around it?
> 
> 3: when a part is placed in the assembler, will it be removed from the storagechunk and will rocketstats get recalculated? (thrust, weight) This is important for when the rocket is disassembled during repair so it does not dulicate parts
> 
> 4: what happens when the player removes the repaired part from the assembler output before the station can take it back?
> 
> 5: are the bugs reported from discord fixed?
> 
> If the system is ready and merged I will probably modify it to make little robots move the parts around into the assembler and back to the rocket

1: 
Rocket is disconnects from repair station on launch, and all repair stats clears from the service station.
Rocket stats will be recalculated when it launches, so rocket without engines cannot start.
If assembler destroyed, it will be disconnected from the service station and all things assigned to it will be lost. Very sad.
Destroying the service station making your life some... unstable, because parts repairing at the moment would stuck in assemblers. Now you need to disassemble the rocket to make it work again.

2:
There is a button inside the interface, additionally you can toggle rescan by redstone.

3:
Before placing part into assembler, part is removing from `StorageChunk`, yes. As already stated, `RocketStats` gets recalculated on every launch top avoid such mistakes.

4:
Very, very sad. You broke the process, now the only way is to repair rocket by hand.

5:
All reported bugs from discord were fixed

**Pull request merged**
